spring:
  application:
    name: userService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy
    password: 123
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7770/eureka,http://eureka01:7771/eureka