server:
  port: 7771

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: eureka01
    prefer-ip-address: false
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka02:7770/eureka