server:
  port: 7770

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: eureka02
    prefer-ip-address: false
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01:7771/eureka