server:
  port: 6770

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7770/eureka,http://eureka01:7771/eureka

spring:
  cloud:
    gateway:
      #路由配置,一个列表,包含很多信息
      routes:
        - id: borrow-service #路由名称
          uri: lb://borrowService #路由地址,lb表示使用负载均衡微服务(lordBalance),也可以使用http正常转发
          predicates: #路由规则,断言什么请求会被路由
            - Path=/dbBorrow/** #只要访问这个路径,一律都被路由到上面指定的服务
        - id: book-service
          uri: lb://bookService
          predicates:
            - Path=/dbBook/**
          filters: #添加过滤器
            - AddRequestHeader=X-Request-Id, 123456
            #AddRequestHeader就是添加请求头信息
  application:
    name: gateWay